#!/bin/sh
# try and keep this pure bourne shell
# minimal clone of raspberry tool vcgencmd - for use with Android rpicheck and rock64 SBC

command=$1
case ${1} in
        measure_clock)
                case ${2} in
                        arm)
                                # awk is probably overkill....
				value=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq | awk '{print $1 * 1000}'`
                                echo 'frequency(45)='${value}
                                exit
                        ;;
                        core)
                                value=0  # TODO / FIXME
                                echo 'frequency(1)='${value}
                                exit
                        ;;
                # TODO anything else thrown an error/debug
                esac
                exit
                ;;
        measure_temp)
                # awk is probably overkill....
                value=`cat /sys/class/thermal/thermal_zone0/temp | awk '{printf "%.3f\n", $1 / 1000}'`
                # NOTE RasPi Check expects floating point result, integer result displays as 0 degrees in RasPi Check v1.8.12
                echo 'temp='${value}"'C"
                exit
                ;;
        measure_volts)
                case ${2} in
                        core)
                                value=0  # TODO / FIXME
                                echo 'volt='${value}'.0000V'
                                exit
                        ;;
                # TODO anything else thrown an error/debug
                esac
                ;;
        version)
                echo 'Nov  4 2018 16:31:07'
                echo 'Copyright (c) 2012 rock64'
                echo 'version rock64_TODO (clean) (release)'
                exit
                ;;
esac


exit
# remove/comment out exit about for debug logging
# NOTE may need allow permissions on file:
#	sudo chmod a+w /var/log/vcgencmd.log


# if we got here, unrecognized parameter
# log it for debugging purposes

# on this device /var/log is ramfs folder2ram
LOG=/var/log/vcgencmd.log
LOG=/tmp/vcgencmd.log


date >> ${LOG}
echo PARAM star ${*} PARAM >> ${LOG}
echo PARAM one ${1} PARAM >> ${LOG}
echo PARAM two ${2} PARAM >> ${LOG}
echo '=============' >> ${LOG}

